set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER   gcc)
set(CMAKE_CXX_COMPILER g++)

# Use MinGW
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-mingw32)
set(CMAKE_C_COMPILER_TARGET   x86_64-w64-mingw32)
